myrecipes/myrecipes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^recipes/', include('recipes.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.error_404, name='404'),
    # Accounts agrega opcion de login y logout
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

myrecipes/recipes/urls.py
from django.conf.urls import url

from . import views

# Namspace: https://docs.djangoproject.com/en/1.10/intro/tutorial03/#namespacing-url-names
app_name = 'recipes'
# Url list
urlpatterns = [
    # ex: /recipes/
    url(r'^$', views.Index.as_view(), name='index'),
    # ex: /recipes/1/
    url(r'^(?P<pk>[0-9]+)/$', views.Detail.as_view(), name='detail'),
    # ex: /recipes/new/
    url(r'^new/$', views.RecipeCreate.as_view(), name='new'),
]

myrecipes/common/models.py
from django.db import models

# Create your models here.

myrecipes/recipes/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


class DishType(models.Model):
    # Starter, main, dessert, etc.
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description

    class Meta:
        """
        Modifica el nombre de la clase que se mostrara en el admin
        """
        verbose_name = 'Tipo de plato'
        verbose_name_plural = 'Tipos de platos'


class FoodType(models.Model):
    # vegetarian, gluten free, etc.
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description


class Difficult(models.Model):
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description


class Thematic(models.Model):
    # spanish, mexican, chinese, tc.
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description


class PublicTarget(models.Model):
    # children, birthday, professional events, etc.
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description


class IngredientAlternative(models.Model):
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description


class Ingredient(models.Model):
    description = models.CharField(max_length=50)
    ingredient_alternative = models.ManyToManyField(IngredientAlternative, blank=True)

    def __str__(self):
        return self.description


class Recipe(models.Model):
    # fieldsets = (
    #     (None, {
    #         'fields': ('title', 'foo')
    #     }),
    #     ('Avanzadas', {
    #         'classes': ('collapse',),
    #         'fields': ('reuse',)
    #     })
    # )
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField()
    short_description = models.CharField(max_length=140, verbose_name='Descripción breve')
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, default=1)
    food_type = models.ManyToManyField(FoodType)
    difficult = models.ForeignKey(Difficult, default=1, on_delete=models.CASCADE)
    directions_time = models.PositiveSmallIntegerField(verbose_name='Tiempo de preparación')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Precio (€)')
    person_number = models.PositiveSmallIntegerField(verbose_name='Comensales', default=1)
    thematic = models.ForeignKey(Thematic, on_delete=models.CASCADE, default=1)
    public_target = models.ForeignKey(PublicTarget, on_delete=models.CASCADE, default=1)
    ingredients = models.ManyToManyField(Ingredient)
    directions = models.TextField()
    calories = models.PositiveSmallIntegerField(blank=True, null=True)
    nutritional_value = models.PositiveSmallIntegerField(blank=True, null=True)
    conservation = models.CharField(max_length=255, blank=True, null=True)
    # FIXME Este campo podria ser un textfield
    # o mejor un enlace a otra receta existente
    reuse = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    author = models.ForeignKey(User)
    publish = models.BooleanField(default=False)

    def __str__(self):
        return self.title

# FIXME Crear meta para que siempre ordene por
# datetime_modificated, tanto en admin como front
# class RecipeX(Recipe):
#
#     @staticmethod
#     def foo():
#         print("hi")

myrecipes/common/views.py
from django.shortcuts import render

# Create your views here.

myrecipes/myrecipes/views.py
from django.http import HttpResponse


def error_404(request):
    return HttpResponse("<h1>Not Found </h1>")

myrecipes/recipes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Recipe


class Index(generic.ListView):
    """
    Recipe list
    """
    template_name = 'recipes/index.html'
    context_object_name = 'latest_recipes_list'
    paginate_by = 5

    def get_queryset(self):
        """
        Return the last five published recipes (not including those set to be
        published in the future).
        """
        return Recipe.objects.order_by('datetime_modificated')
        # return Recipe.objects.values_list('id', 'title').order_by('datetime_modificated')[:5]


class Detail(generic.DetailView):
    """
    Recipe info
    """
    def get_queryset(self):
        """
        Excludes any recipes that aren't published yet.
        """
        return Recipe.objects.all()

    # def get_context_data(self, **kwargs):
    #     """
    #     Excludes any recipes that aren't published yet.
    #     """
    #     context = super(Detail, self).get_context_data(**kwargs)


def new_recipe(request):
    """
    New recipe form
    """
    return render(request, 'recipes/base.html')


class RecipeCreate(LoginRequiredMixin, generic.CreateView):
    model = Recipe
    # Al insertar redirecciona a la misma url de insercion
    # se usa reverse_lazy xq en este punto la URL no ha sido
    # cargada cuando se importa el fichero
    success_url = reverse_lazy('recipes:new')
    # Campos a mostrar en el formulario,
    # si no se especifica muestra todos
    fields = ['title', 'short_description']

    def form_valid(self, form):
        # Al hacer la validacion, debemos agregar a la receta
        # el autor de esta. Django nos devuelve el usuario
        # mediante el objeto request. Debemos estar logeados
        # para que funcione adecuadamente.
        # Docu: https://docs.djangoproject.com/en/1.10/topics/class-based-views/generic-editing/#model-forms
        # En la segunda nota se aclara
        form.instance.author = self.request.user
        redirect_url = super(RecipeCreate, self).form_valid(form)
        # messages.success(self.request, 'Creada receta. La receta está desactivada hasta que un administrador lo revise. ')
        return redirect_url

myrecipes/common/templates/common/base.html
{% load i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Recipe</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block extra_head %}
    <!-- custom extra_head -->
    {% endblock extra_head %}
</head>
<body>
{% block body %}
<h1>Hola Mundo!</h1>
{% endblock body %}
<!-- Bootstrap -->
<script src="https://code.jquery.com/jquery-3.2.0.min.js" integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% block extra_body %}
<!-- custom extra_body -->
{% endblock extra_body %}

</body>
</html>

myrecipes/common/templates/common/swiper-form-fields.html
<!-- Slider main container -->
    <div class="swiper-container">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            {% for field in form %}
            <div class="swiper-slide">
                {{ field }}
                {# {{ field.errors }} #}
                {# {{ field.label_tag }} {{ field }} #}
            </div>
            {% endfor %}
            <div class="swiper-slide">
                ¡Gracias!
            </div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>

myrecipes/common/templates/common/swiper.html
{% extends "common/base.html" %}
{% load staticfiles %}

{% block extra_head %}
<!-- Swiper -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css">
<link rel="stylesheet" href="{% static "css/styles-swiper.css" %}">
<!-- /Swiper -->
{% endblock extra_head %}

{% block extra_body %}
<!-- Swiper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.jquery.min.js"></script>
<script src="{% static "js/main-swiper.js" %}"></script>
<!-- /Swiper -->
{% endblock extra_body %}

myrecipes/recipes/templates/recipes/index.html
{% if latest_recipes_list %}
    <ul>
    {% for recipe in latest_recipes_list %}
    {# Namespace: https://docs.djangoproject.com/en/1.10/intro/tutorial03/#namespacing-url-names #}
        <li><a href="{% url 'recipes:detail' recipe.id %}">{{ recipe.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

myrecipes/recipes/templates/recipes/recipe_form.html
{% extends "common/swiper.html" %}
{% load swiper %}
{% block body %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{# Form: https://docs.djangoproject.com/en/1.10/intro/tutorial04/ #}
<form action="{% url 'recipes:new' %}" class="viewform erk-form form-horizontal" id="erk-form" method="post">
    {% csrf_token %}
    {% swiper_form %}
    {# <input type="submit" value="Guardar" /> #}
</form>

{% endblock body %}

myrecipes/recipes/templates/recipes/recipes_detail.html
<h1>{{ object.name }}</h1>

<p>{{ object.short_description }}</p>